import '../styles/globals.css';

export const metadata = {
  title: 'Vibe Destiny',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>Vibe Destiny</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}